PREFIX : <http://example.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <https://www.wikidata.org/wiki/Property:>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?integrante ?miembro ?miembroLabel ?ciudadNacimiento ?ciudadNacimientoLabel
WHERE {
  {
    SELECT DISTINCT ?integrante ?miembro ?ciudadNacimiento
    WHERE {
      BIND(:Mauricio_Beltran AS ?integrante)
      ?integrante p:P1775 ?artista .
      ?artista wd:Q52630241 ?miembro .

      SERVICE <https://query.wikidata.org/sparql> {
        ?miembro wdt:P19 ?ciudadNacimiento .
        ?miembro wdt:P1303 wd:Q6607 .
      }
    }
    ORDER BY ?miembro
    LIMIT 2
  }
  UNION
  {
    SELECT DISTINCT ?integrante ?miembro ?ciudadNacimiento
    WHERE {
      BIND(:Rangi_Becerra AS ?integrante)
      ?integrante p:P1775 ?artista .
      ?artista wd:Q52630241 ?miembro .

      SERVICE <https://query.wikidata.org/sparql> {
        ?miembro wdt:P19 ?ciudadNacimiento .
        ?miembro wdt:P1303 wd:Q6607 .
      }
    }
    ORDER BY ?miembro
    LIMIT 2
  }
  UNION
  {
    SELECT DISTINCT ?integrante ?miembro ?ciudadNacimiento
    WHERE {
      BIND(:Felipe_Troncoso AS ?integrante)
      ?integrante p:P1775 ?artista .
      ?artista wd:Q52630241 ?miembro .

      SERVICE <https://query.wikidata.org/sparql> {
        ?miembro wdt:P19 ?ciudadNacimiento .
        ?miembro wdt:P1303 wd:Q6607 .
      }
    }
    ORDER BY ?miembro
    LIMIT 2
  }

  SERVICE <https://query.wikidata.org/sparql> {
    SERVICE wikibase:label {
      bd:serviceParam wikibase:language "es,en" .
    }
  }
}



